# Generated by Django 5.1 on 2024-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(default='M', max_length=255),
        ),
    ]
