# Generated by Django 5.1 on 2024-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
