# Generated by Django 5.1 on 2024-09-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_date_cancelled_order_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='image',
            field=models.URLField(default='vjsdjvsk'),
            preserve_default=False,
        ),
    ]
