# Generated by Django 5.1 on 2024-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
