# Generated by Django 5.1 on 2024-09-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_user_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
