# Generated by Django 5.1 on 2024-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', max_length=255),
            preserve_default=False,
        ),
    ]
